application: gg-bi-140610
runtime: python27
api_version: 1
threadsafe: yes
version: initial

handlers:
- url: .*
  script: main.app

libraries:
- name: pycrypto
  version: "2.6"
- name: ssl
  version: "2.7"
